# Generated by Django 5.1.6 on 2026-09-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_working_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='days', max_length=10)),
                ('requires_allocation', models.BooleanField(default=True, help_text='If False, employees can request unlimited time off without pre-allocated balance tracking')),
                ('is_paid', models.BooleanField(default=True, help_text='Informs future payroll calculation whether this time off is paid or unpaid')),
                ('requires_approval', models.BooleanField(default=True, help_text='Requires explicit manager/HR approval')),
            ],
            options={
                'verbose_name': 'Time Off Type',
                'verbose_name_plural': 'Time Off Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total granted leave amount (e.g. 20.00 days)', max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, help_text='Expiry date for allocation. Leave blank for no expiry.', null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='employees.employee')),
                ('time_off_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='time_off.timeofftype')),
            ],
            options={
                'verbose_name': 'Time Off Allocation',
                'verbose_name_plural': 'Time Off Allocations',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('refused', 'Refused'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('allocation', models.ForeignKey(blank=True, help_text='Allocation drawn from if time off type requires allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='time_off.timeoffallocation')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='employees.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='employees.employee')),
                ('time_off_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='time_off.timeofftype')),
            ],
            options={
                'verbose_name': 'Time Off Request',
                'verbose_name_plural': 'Time Off Requests',
                'ordering': ['-date_from'],
            },
        ),
    ]
