# Generated by Django 5.1.6 on 2026-09-05 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_off', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='overflow_unpaid_request',
            field=models.ForeignKey(blank=True, help_text='Auto-created unpaid leave request for excess days', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_overflow_requests', to='time_off.timeoffrequest'),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='paid_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Duration covered by paid leave balance', max_digits=6),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='unpaid_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Excess duration automatically routed to unpaid leave', max_digits=6),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='reason',
            field=models.TextField(blank=True, help_text='Leave note explaining why employee is requesting leave'),
        ),
    ]
