# Generated by Django 5.1.6 on 2026-09-05 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('working_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working_schedule',
            field=models.ForeignKey(blank=True, help_text='Assigned shift schedule for expected working hours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='working_schedule.workingschedule'),
        ),
    ]
