# Generated by Django 5.1.6 on 2026-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_working_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
