# Generated by Django 5.1.6 on 2026-09-06 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('payroll', '0006_alter_salaryrule_options_salaryrule_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payslip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='payroll.payslip'),
        ),
    ]
