# Generated by Django 5.1.6 on 2026-09-05 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_working_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('wage', models.DecimalField(decimal_places=2, help_text='Base monthly wage amount', max_digits=12)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, help_text='Leave blank if contract is open-ended', null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Product', 'Product'), ('HR', 'HR'), ('Finance', 'Finance'), ('Sales', 'Sales'), ('Operations', 'Operations')], max_length=50)),
                ('job_position', models.CharField(max_length=100)),
                ('salary_structure_placeholder', models.CharField(blank=True, help_text='Temporary text note indicating intended salary structure name. Will be replaced by real ForeignKey when payroll app is created.', max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-date_start'],
            },
        ),
    ]
