# Generated by Django 5.1.6 on 2026-09-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
