# Generated by Django 5.1.6 on 2026-09-05 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_migrate_expired_contracts_to_running'),
        ('working_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='working_schedule',
            field=models.ForeignKey(blank=True, help_text='Optional shift schedule for expected working hours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='working_schedule.workingschedule'),
        ),
    ]
