# Generated by Django 5.1.6 on 2026-09-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(default='My Company', max_length=100)),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('gross', 'Gross'), ('net', 'Net')], default='basic', max_length=20)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='payroll.salarystructure')),
            ],
            options={
                'verbose_name': 'Salary Rule',
                'verbose_name_plural': 'Salary Rules',
                'ordering': ['category', 'name'],
            },
        ),
    ]
