# Generated by Django 5.1.6 on 2026-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrule',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='percentage_basis_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salaryrule',
            name='amount_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('formula', 'Formula')], default='fixed', max_length=20),
        ),
    ]
