# Generated by Django 5.1.6 on 2026-09-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payslipadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='expected_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='worked_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
