# Generated by Django 5.1.6 on 2026-09-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payslip_actual_hours_payslip_expected_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryrule',
            options={'ordering': ['sequence', 'id'], 'verbose_name': 'Salary Rule', 'verbose_name_plural': 'Salary Rules'},
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='sequence',
            field=models.IntegerField(default=10),
        ),
    ]
