# Generated by Django 5.1.6 on 2026-09-05 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(choices=[('fixed', 'Fixed'), ('flexible', 'Flexible')], default='fixed', max_length=20)),
                ('company_name', models.CharField(default='My Company', max_length=100)),
            ],
            options={
                'verbose_name': 'Working Schedule',
                'verbose_name_plural': 'Working Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=0, help_text='Break duration in minutes')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='working_schedule.workingschedule')),
            ],
            options={
                'verbose_name': 'Working Schedule Line',
                'verbose_name_plural': 'Working Schedule Lines',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('schedule', 'day_of_week')},
            },
        ),
    ]
