# Generated by Django 5.1.6 on 2026-09-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_working_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, help_text='Leave blank if employee has not checked out yet', null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='present', max_length=20)),
                ('is_manual_correction', models.BooleanField(default=False, help_text='Flags whether this record was manually created or corrected by an authorized user')),
                ('notes', models.TextField(blank=True, help_text='Optional comments or explanation for manual corrections')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-check_in'],
            },
        ),
    ]
